### ISSUE TITLE
Unreal pixel streaming Marketplace extension

### ISSUE THREAD

**Issue by kpradp** [Azure/Unreal-Pixel-Streaming#30]
Hi, 

I am hosting sample unreal app using Azure marketplace extension. For auto scale configuration. However I am getting the error as 

“All cirrus server are in use. Retrying”

I retired deploying from the scratch , still I am getting the error. Is there any thing I am missing. 

The app works fine on local machine and with standalone VM. 

Is there any Linux option available for Azure as in AWS 

https://aws.amazon.com/blogs/gametech/unreal-engine-pixel-streaming-in-aws-with-ubuntu-os/

**Comment by microsoftman** [comment]
Hello,  usually this happens if the UE4 app and the signaling server are not working somehow to communicate back to the Matchmaker. Can you login to one of the VMSS instances and see what the C:\gaming logs are showing?  This should give you a good idea of what’s happening. Also, you can try to go directly to a VMSS instance to verify if they are working regardless of the MM. also you can check the same logs on the MM too, but likely an issue on the SS. 

The marketplace version currently only supports Windows, but Linux is a a roadmap feature.

**Comment by kpradp** [comment]
Ok I will check that. Unfortunately I deleted since it's not working. Will redo and check. 

I am using the source build of UE 5.01 , is that something to do with it ? Is there any place where I can download these mm and signalling server files and replace before re uploading ?

**Comment by microsoftman** [comment]
So UE5 should work, as long as you rename the UE5 parent folder name from "Windows" to "WindowsNoEditor" like the old UE4 naming. This is fixed in a future release to not require this, but I don't believe Epic has released this yet.

**Comment by kpradp** [comment]
Ok. I didn't rename the folder. I think that's reason my streams aren't running. 
I will re upload check and let you know.

**Comment by kpradp** [comment]
Can you say me the folder path of the pixel streaming build for unreal engine 5.
Which folder I need to rename ?

**Comment by Camouflagestudios** [comment]
We have packaged a project for pixel streaming in Azure .
We succeeded to deploy in azure using single vm , matchmaker for one region and the a traffic manager with multi region
We tried the unreal pixel streaming at scale available on azure market place .
We followed the tutorial in the documentation and each time the deployment fails with error saying that the application insight doesnt support the classic mode of the resource group and it needs to be of workspace base, any clues??

**Comment by microsoftman** [comment]
Hi @kpradp, I realized I never got back to you on this question -- did you figure it out or shall we follow-up offline?  The latest Marketplace solution has a fix to work for either UE4 or UE5 naming automatically now, as long as you zip up the final exported folder (i.e., Windows or WindowsNoEditor), not the contents of the folder (we are looking to improve that logic as well).

**Comment by microsoftman** [comment]
@Camouflagestudios thanks for reach out on this.  I just tried to deploy to East US and was successful -- can you try East US as a test and see if this issue is still happening and something specific to your settings used?  Also, which region(s) did you try, I will try your region as well to verify.

**Comment by kpradp** [comment]
@microsoftman  I will check this and let you know if there are any challenges.

Meanwhile we are looking solutions for pixel streaming using docker or k8 with scalable option as mentioned in 

https://github.com/oracle-quickstart/oke-unreal-pixel-streaming

Is there any roadmap for k8 implementation ?

**Comment by microsoftman** [comment]
@kpradp we originally started with K8s as the plan, but didn't know if customers wanted all that complexity so just went with the simplier VM Scale Sets -- would you prefer K8s with something like AKS managing the solution?

**Comment by kpradp** [comment]
@microsoftman yes off course. We can educate the dev ops team and they will be able to do the part. A good documentation will help us to achieve this.
