### ISSUE TITLE
Pixel Streaming in Unreal Engine 5.2

### ISSUE THREAD

**Issue by WilBlanchardPR** [Azure/Unreal-Pixel-Streaming#44]
My team and I have been attempting to deploy an Unreal application that uses the most up-to-date version of the Unreal Engine (5.2 at the time of writing) in Azure.  Looking at the repository, it seems like the last time it was updated was for 4.27 a few years back.  Since then, there have been quite a few changes made to the engine.  

I was wondering if there were plans to update this repository to support version 5.2 and beyond.  I also wanted to ask what changes were made here from Epic's Pixel Streaming Infrastructure repository to make it "Azure-ready" so we could make the necessary modifications ourselves if need be.

Thank you so much!

**Comment by microsoftman** [comment]
Hello @WilBlanchardPR, this repository is no longer being updated going forward, and the new feature work was put into Epic's Marketplace solution in Azure (https://azuremarketplace.microsoft.com/en-us/marketplace/apps/epicgames.unreal-pixel-streaming?tab=overview), but we kept this around for folks wanting to use Terraform instead of ARM. The Marketplace solution does support UE5 as the binary, but the web UI for Pixel Streaming is not updated to the latest 5.2. Customers are using UE5 with the Marketplace solution (a UE5 exe works). I believe the tweaks for this repo were also allowing UE5, though the nodejs UI/code was not updated to the latest UE5 code... just allows the UE5 exe to work (mostly the WindowsNoEditor name changed in UE5).

**Comment by AMGI-Pipeline** [comment]
Hey @microsoftman, That [link to the Azure Marketplace solution](https://azuremarketplace.microsoft.com/en-us/marketplace/apps/epicgames.unreal-pixel-streaming?tab=overview) is no longer valid.  Is there a way to use pixelstreaming at scale with Azure using UE5.3 applications?

**Comment by microsoftman** [comment]
Hi @AMGI-Pipeline, Epic Games has taken down the Marketplace solution due to shifting priorities and being able to support it going forward; however, they did Open Source it here if you want to check it out:  https://github.com/ue4plugins/UnrealPixelStreamingOnAzure

**Comment by AMGI-Pipeline** [comment]
@microsoftman, Thank you for the explanation and the link to the repo.
