### ISSUE TITLE
runAzure.bat - cannot find module

### ISSUE THREAD

**Issue by mbaltera-10408** [Azure/Unreal-Pixel-Streaming#8]
Looks like Unreal 4.27 changes some pathing that is impacting the signaling server scripts.

Running: node.exe cirrus --peerConnectionOptions="{ \"iceServers\": [{\"urls\": [\"stun:stun.l.google.com:19302\"]}] }" --publicIp=20.94.172.80
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'C:\Program Files\Epic Games\UE_4.27\Samples\PixelStreaming\WebServers\SignallingWebServer\platform_scripts\cmd\cirrus'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
Press any key to continue . . .

**Comment by mbaltera-10408** [comment]
modifying
$Arguments = @("**../../cirrus**", "--peerConnectionOptions=""$peerConnectionOptions""", "--publicIp=$PublicIp")
fixes the issue.

**Comment by microsoftman** [comment]
Thanks @mbaltera-10408, we'll check out these changes for 4.27 and update the repo. Thanks for sharing your findings on this change.

**Comment by microsoftman** [comment]
This is fixed for 4.26 and 4.27 versions, which need to account for the different cirrus location.  See the Merged code from khaines regarding this tweak.  By default we assume 4.27 going forward, as that is the GA version of pixel streaming, and will no longer be actively developing to support 4.26 and below versions of Pixel Streaming due to the bugs and stability issues that were present in 4.26.
